### ISSUE TITLE
不要な半角スペースがあるためにエラーとなっています

### ISSUE THREAD

**Issue by imony** [tsukasa-tsukano/study_Flask#2]
https://github.com/tsukasa-tsukano/study_Flask/blob/c6c9abd8445e170913ab01f49f114e6c5ec0de6d/templates/index.html#L12

Jinja2のfor構文は、{% for %} で始まり、 {% endfor %} で終わります。
上記コードの場合、開始部分の{と%の間にスペースが入っているためにエラーとなっています。

**Comment by tsukasa-tsukano** [comment]
無事解決いたしました
